[project]
name = "reddit-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "praw>=7.8.1",
    "tqdm>=4.67.1",
]
